prj_sharkommerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url


urlpatterns = [
    path('', include('sharkommerce.urls', namespace="sharkommerce")),
    path('admin/', admin.site.urls),
]

sharkommerce/urls.py
from django.conf.urls import url
from django.urls import path
from django.views import static
from prj_sharkommerce import settings
from . import views

app_name = 'sharkommerce'

urlpatterns=[
    url(r'^$', views.index, name='index'), #così, si apre subito sulla main page, non c'è bisogno di aprire /sharkommerce; è ok?
    path('item/<int:product_id>/', views.item, name='item'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^cart/$', views.cart, name='cart'),
    #view utilizzata per togliere l'elemento dal carrello
    path('cart/remove/<int:product_id>/',views.removeFromCart, name='removeFromCart'),
    url(r'^logout/$', views.logout_view, name='logout'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    url(r'^profile/(?P<user_id>[0-9]+)/seller_review$', views.seller_review, name='seller_review'),
    url(r'^profile/product_review$', views.product_review, name='product_review'),
    #utilizzato per avere il json dei prodotti in una certa category+subcategory
    path('products/<str:cat>/<str:subcat>/', views.product_cat, name='product_cat'),
    # used to get media files
    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': settings.MEDIA_ROOT}),
    path('products', views.products, name='products'),
    path('purchase', views.purchase, name='purchase')


]

sharkommerce/models.py
import os
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string


class Buyer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    address = models.CharField(max_length=60)
    birth_date = models.DateField()

    # controlla se l'utente ha fatto un acquisto presso il venditore prima di inserire la recensione
    def check_if_bought(self, seller):
        return Purchase.objects.filter(buyer=self, product__seller=seller).exists()

    def __str__(self):
        return self.user.username


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    store = models.CharField(max_length=50)
    average_rate = models.DecimalField(max_digits=4, decimal_places=2, default=0) # con il calcolo, questo record non mi serve

    def __str__(self):
        return self.store

    def calculateAverageRate(self):#vedi cosa deve tornare
        reviews = SellerReview.objects.filter(seller=self)
        if not reviews.exists():
            return 0 #prima c'era un return False
        sum = 0
        for rev in reviews:
            sum += rev.vote
        return round(sum / reviews.count(),2)


#un acquirente può recensire il venditore una sola volta
class SellerReview(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    buyer = models.ForeignKey(Buyer, null=True, on_delete=models.SET_NULL) # ma perchè null=True se è in foreign key?!
    date = models.DateField()
    vote = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    title = models.CharField(max_length=100)
    description = models.TextField()

    class Meta:
        unique_together = ("seller", "buyer")


class Category(models.Model):
    cat_name = models.CharField(max_length=100)
    subcat_name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.cat_name} {self.subcat_name}"

    class Meta:
        unique_together = ("cat_name", "subcat_name")
        verbose_name_plural = "categories"


def get_img_name(instance, *args):
    return os.path.join(instance.seller.user.username, f"img_{get_random_string(length=16)}")


class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    categories = models.ForeignKey(Category, on_delete=models.RESTRICT)
    name = models.CharField(max_length=100)
    image = models.ImageField(blank=False, upload_to=get_img_name)
    qty = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)
    description = models.TextField()
    #questo deve avere un average rate

    class Meta:
        unique_together = ('id', 'seller')

    def __str__(self):
        return self.name

    #se il seller vuole fare refill dei prodotti?
    def update_qty(self, qty):
        if qty <= self.qty and qty > 0:
            self.qty -= qty
            self.save()
        else:
            raise ValueError("Error during update product's quantity")

    def is_available(self):
        return self.qty > 0


    def calculateAverageRate(self):
        reviews = ProductReview.objects.filter(purchase__product=self)
        if not reviews.exists():
            return "Nessuna recensione inserita"
        sum = 0
        for rev in reviews:
            sum += rev.vote
        return round(sum / reviews.count(), 2)


class Purchase(models.Model):
    buyer = models.ForeignKey(Buyer, on_delete=models.SET_NULL, null=True) #se sono in chiave, non possono essere null
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField(default=1)
    date = models.DateField()
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0.00)


    class Meta:
        unique_together = ('product', 'date', 'buyer') #va bene cosi o mi conviene usare i numeri gentilmente offerti da Django? per la migration delle prod rev, viene sfruttato il fatto che siano unique

    def get_tot_purc(self):
        return self.qty

    def __str__(self):
        return f"{self.product.name} {self.buyer} {self.date}"


class ProductReview(models.Model):
    purchase = models.ForeignKey(Purchase, on_delete=models.CASCADE)
    vote = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(10)])
    title = models.CharField(max_length=100)
    description = models.TextField()
    average_rate = models.DecimalField(max_digits=4, decimal_places=2, default=0) #questa va cancellata, non la userai mai, ma per le magie di sqlite è un casino,
    date = models.DateField(null=True)                                                                                #quindi lo faremo col progetto definitivo da subito

sharkommerce/views.py
import datetime
from django.contrib import messages
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, reverse
from sharkommerce.Utils.SellerProfileUtils import *
from sharkommerce.Utils.ItemUtils import *
from sharkommerce.forms_class import RegisterForm, LoginForm, ProductForm, ReviewForm, FiltersForm, ItemForm, \
    ProductReviewForm
from .models import Category, Seller, Buyer, Product, Purchase, SellerReview, ProductReview
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse



def index(request):
    try:
        is_seller = Seller.objects.get(user_id=request.user.id)
    except Seller.DoesNotExist:
        is_seller = False

    return render(request, 'sharkommerce/homefile.html',{'is_seller': is_seller})

#questa view rimuove gli oggetti dal carrello e fa redirect alla view del carrello
def removeFromCart(request, product_id):
    del request.session["cart"][str(product_id)] # devo inserire il controllo sul fatto che esista nel carrello?
    request.session.save()
    return HttpResponseRedirect(reverse('sharkommerce:cart'))


# controllo che il numero di prodotti inseriti nel carrello sia effettivamente acquistabile ( un utente potrebbe
# aggiungere al carrello più prodotti di quelli disponibili, sommandone ad es il massimo possibile dello stock in più
# giri
def check_qty_available(items, cart):
    for prod in items:
        if prod.qty < cart[str(prod.id)]:
            return False
    return True


@login_required
def purchase(request):
    if not Buyer.objects.filter(user=request.user).exists():
        messages.error(request, '*puoi effettuare acquisti solo con un profilo da acquirente*')
        return HttpResponseRedirect(reverse('sharkommerce:login'))
    if request.method == 'POST':
        try:
            if request.session["cart"]:
                items = Product.objects.filter(id__in=request.session["cart"])
                if check_qty_available(items, request.session["cart"]):
                    purch = [Purchase(buyer_id=request.user.id, product=i, qty=request.session["cart"][str(i.id)],
                                      date=datetime.date.today(), price=i.price) for i in items]
                    for p in items:
                        p.update_qty(request.session["cart"][str(p.id)])
                    try:
                        Purchase.objects.bulk_create(purch)
                        request.session.flush()
                        messages.success(request, 'Acquisto inserito')
                        return HttpResponseRedirect(reverse('sharkommerce:profile', args=[request.user.id]))
                    except IntegrityError:
                        messages.error(request, '* Errore: prova più tardi *')
                else:
                    messages.error(request, '*troppi oggetti nel carrello rispetto la disponibilità*')
        except KeyError:
            request.session["cart"] = {}
            messages.error(request, '* Carrello vuoto *')
    return HttpResponseRedirect(reverse('sharkommerce:cart'))


@require_GET
def cart(request):
    items = []
    tot = 0
    try:
        if request.session["cart"]:
            items = Product.objects.filter(id__in=request.session["cart"])
        if len(items) > 0:
            for elem in items:
                tot += elem.price * request.session["cart"][str(elem.id)]
    except KeyError:
        request.session["cart"] = {}

    context = {'items': items, 'prod_qty': request.session["cart"], 'tot': tot, 'logged':request.user.is_authenticated} #passare la quantità così non mi convince

    return render(request, 'sharkommerce/cart.html', context)


#le funzioni utilizzate che non compaiono in questa classe sono sharkommerce.Utils.ItemUtils
def item(request, product_id):
    item = get_object_or_404(Product, pk=product_id)
    avg_rate = item.calculateAverageRate()  #è meglio se ha direttamente la colonna nel model; nel caso, mettilo in un try catch se non ha recensioni
    reviews = ProductReview.objects.filter(purchase__product=item)
    items_same_purch = get_items_in_same_purchase(item)
    recommended_items = []
    is_logged = request.user.is_authenticated
    # i candidati ideali per gli oggetti raccomandati sono gli oggetti più acquistati con l'oggetto che si sta guardando;
    # se non ce ne sono abbastanza si prendono gli oggetti della stessa categoria più acquistati ( o comunque oggetti
    # della stessa categoria, se non dovessero essercene di acquistati ). Se proprio non sono stati inseriti neanche
    # abbastanza oggetti della stessa categoria, vengono presi oggetti di altre categorie.
    for i in items_same_purch:
        recommended_items.append(Product.objects.get(id=i["product_id"]))
    if len(recommended_items) < 3:
        same_cat_items = get_items_same_category_more_bought(item)
        while len(recommended_items) != 3 and len(same_cat_items) != 0:
            recommended_items.append(Product.objects.get(id=same_cat_items.pop(0)['id']))
        if len(recommended_items) < 3:
            n_mancanti = 3-len(recommended_items)
            recommended_items = recommended_items + list(Product.objects.all().order_by('?')[:n_mancanti])
    item_form = ItemForm(max_qty = Product.objects.get(id=product_id).qty)
    context = {'item': item, 'avg_rate': avg_rate, 'reviews': reviews, 'recommended_items': recommended_items, 'item_form': item_form, 'is_logged':is_logged}
    if request.method == 'POST':

        item_form = ItemForm(request.POST, max_qty=Product.objects.get(id=product_id).qty)
        if item_form.is_valid():
            data = item_form.cleaned_data
            #request.session.flush()
            if "cart" not in request.session:
                #sarà popolato da id, qty per ogni prodotto aggiunto
                request.session["cart"] = {}
            # se l'id del prodotto non è presente nel carrello, viene aggiunto, con la rispettiva quantità; sennò, si
            # prende il suo valore e si somma alla nuova quantità. Il cast a str serve perchè dopo la save la chiave
            # viene trasformata in str anche se partiva come int.
            request.session["cart"][str(product_id)] = request.session["cart"].get(str(product_id), 0) + data["qty"]
            request.session.save()
        else:
            print("errore: quantità di prodotto selezionato errata")

    return render(request, 'sharkommerce/item.html', context)


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('sharkommerce:index'))


def login_view(request):
    login_form = LoginForm()
    context = {'login_form': login_form}
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            data = login_form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    next = request.GET.get("next", reverse('sharkommerce:index'))
                    return HttpResponseRedirect(next)
                else:
                    context.update({'errors': '* Your account is not enabled *'})  # controlla
            else:
                context.update({'errors': '* Username or password not correct *'})
        else:
            context.update({'errors': login_form.errors})  # qui non dovrei mai finirci


    return render(request, 'sharkommerce/login.html', context)


# this function prevents the user remove "required" from javascript code.
def check_is_really_compiled(data):
    if data["tipo"] == "Venditore":
        if data["negozio"] == "":
            return False
    if data["tipo"] == "Acquirente":
        if data["indirizzo"] == "":
            return False
        if data["data_nascita"] is None:
            return False
    return True


def register(request):  # da implementare : aggiunta ai gruppi
    register_form = RegisterForm()
    context = {'register_form': register_form}
    if request.method == 'POST':
        register_form = RegisterForm(request.POST)
        context.update({'register_form': register_form})
        if register_form.is_valid():
            data = register_form.cleaned_data
            if User.objects.filter(username=data['username']).exists():
                context.update({'errors': {'username': ['Username yet existant']}})
                return render(request, 'sharkommerce/register.html', context)
            if not check_is_really_compiled(data):
                context.update({'errors': {'last_forms': ['you miss a form']}})
                return render(request, 'sharkommerce/register.html', context)
            user = User.objects.create_user(username=data['username'], email=data['mail'], password=data['password'])
            if data['tipo'] == 'Venditore':
                venditore = Seller(user=user, store=data['negozio'])
                venditore.save()
            elif data['tipo'] == 'Acquirente':
                acquirente = Buyer(user=user, address=data['indirizzo'], birth_date=data['data_nascita'])
                acquirente.save()
            login(request, user)
            return HttpResponseRedirect(reverse('sharkommerce:index'))
        else:
            context.update({'errors': register_form.errors})
            return render(request, 'sharkommerce/register.html', context)
    else:
        return render(request, 'sharkommerce/register.html', context)


#controlla se chi sta visitando il profilo è il proprietario o no
def check_is_visitor_or_owner(request, id_visitor):
    if request.user == id_visitor:
        return True
    return False


def product_review(request):
    if request.method == "POST":
        product_review_form = ProductReviewForm(request.POST)

sharkommerce/templates/sharkommerce/base.html
<!DOCTYPE html>
<html lang="it">
<head>
{% load static %}
  <title>Sharkommerce Portal</title>
    <!--questi sono per la responsiveness-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--CSS di Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <!-- questa è roba di javascript che non dovrebbe servire ma lo scopriremo alla fine -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <!-- Questo è per le icone -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="icon" type="image/png" href="{% static 'sharkommerce/favicon.jpg' %}" sizes="64x64"/>

    <!-- link allo stylesheet esterno -->
    <link rel="stylesheet" type="text/css" href="{% static 'sharkommerce/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'sharkommerce/profiles.css' %}"/>

</head>
<body>
    <div class="jumbotron text-center">
        <h1 class="display-3">Sharkommerce</h1>
        <p class="lead">Un oceano per l'acquaristica</p>
    </div>

    <!-- Static navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand">Sharkommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
                aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'sharkommerce:index' %}">Home <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sharkommerce:products' %}">Prodotti</a>
                </li>
            </ul>
        </div>
        <div class="navbar-nav ml-auto">
            {% if not request.user.is_authenticated %}
                <a href='{% url 'sharkommerce:login' %}' title="login"><i
                        style="margin-right: 1.0em; color: #EEEEEE;{% if request.user.is_authenticated %}display: none;{% endif %}"
                        class="fas fa-sign-in-alt "> login </i></a>
                <a href="{% url 'sharkommerce:register' %}" title="register"><i
                        style="margin-right: 1.0em; color: #EEEEEE; {% if request.user.is_authenticated %}display: none;{% endif %}"
                        class="fas fa-user-plus "> register </i></a>
            {% else %}
                <div class="mr-2" style="color:white ">Benvenuto, {{ request.user.username }}</div>
                <a href='{% url 'sharkommerce:profile' request.user.id %}' title="profile"><i style=" color: #eeeeee;"
                                                                                              class="fas fa-user-alt mr-1">
                    profile </i></a>
            {% endif %}
            <a href='{% url 'sharkommerce:logout' %}' title="logout"><i
                    style=" color: #EEEEEE; {% if not request.user.is_authenticated %}display: none;{% endif %}"
                    class="fas fa-sign-out-alt mr-1"> logout </i></a>
            {% if not is_seller %}
            <a href="{% url 'sharkommerce:cart' %}" title="cart"><i style=" color: #EEEEEE"
                                                                    class="fas fa-cart-plus mr-1"> cart </i></a>
            {% endif %}
        </div>
    </nav>

    {% block content %} {% endblock content %}

    <!-- footer -->
    <div class="navbar fixed-bottom"style="height:40px; background-color: #000000">
        <p class= "text-white"> Sharkommerce é un progetto per il corso di linguaggi dinamici.</p>
    </div>

</body>
</html>

sharkommerce/templates/sharkommerce/cart.html
{% extends 'sharkommerce/base.html' %}
{% load filters %}
{% block content %}
    {% if items|length == 0 %}
        <h4 style="text-align: center; margin-top: 20px"> ancora nessun elemento nel carrello</h4>
    {% else %}
        <h4 style="text-align: center; margin-top: 20px"> Elementi nel carrello:</h4>
        {% if errors or messages %} {# prende tutti i messages #}
            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ errors }}
                {% for mess in messages %}
                    {% if mess.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p>{{ mess }}</p>
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        {% for elem in items %}
            <div class="card w-50 mx-auto" style="margin-top: 20px; margin-bottom: 20px">
                <div class="card-body">
                    <div class="row justify-content:center">
                        <div class="col-md-4">
                            <img src="{{ elem.image.url }}" style="max-width: 200px; max-height: 300px;">
                        </div>
                        <div class="col-md-7 mx-auto">
                            <h3><a href="{% url 'sharkommerce:item' elem.id %}">{{ elem.name }}</a></h3>
                            <p>Prezzo: {{ elem.price }} €</p>
                            {% for id,qty in prod_qty.items %}
                                {% if elem.id|slugify == id %}
                                    <p>Quantita': {{ qty }}</p>
                                    <p>Tot parziale: {{ elem.price | multiply:qty }} €</p>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="col-md-1">
                            <form method="post" enctype="multipart/form-data"
                                  action="{% url 'sharkommerce:removeFromCart' elem.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn">
                                    <i class="fas fa-trash-alt" value="{{ elem.id }}"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <hr>
        <div class="row" style="justify-content:center; margin-bottom: 50px">
            <h4 style="margin-right: 20px">Tot: {{ tot }} €</h4>
            <form method="post" enctype="multipart/form-data" action="{% url 'sharkommerce:purchase' %}">
                {% csrf_token %}
                <input type="submit" class="btn btn-primary" value="Acquista">
            </form>
        </div>
    {% endif %}

{% endblock %}

sharkommerce/templates/sharkommerce/homefile.html
{% extends 'sharkommerce/base.html' %}
{% load static %}
{% block content %}
 <!-- Questo è il carousel -->
<div id="demo" class="carousel slide" data-ride="carousel" style="margin-top:50px; margin-bottom: 80px">
    <ul class="carousel-indicators">
        <li data-target="#demo" data-slide-to="0" class="active"></li>
        <li data-target="#demo" data-slide-to="1"></li>
        <li data-target="#demo" data-slide-to="2"></li>
    </ul>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block mx-auto" src="{% static "sharkommerce/main_carousel_images/vasca1.jpg" %}" alt="marino" >
            <div class="carousel-caption">
                <h3>Marino</h3>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block mx-auto" src="{% static "sharkommerce/main_carousel_images/vasca2.jpg" %}" alt="iwagumi">
            <div class="carousel-caption">
                <h3>Iwagumi</h3>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block mx-auto" src="{% static "sharkommerce/main_carousel_images/vasca3.jpg" %}" alt="malawi">
            <div class="carousel-caption">
                <h3>Malawi</h3>
            </div>
        </div>
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>

{% endblock %}

sharkommerce/templates/sharkommerce/index.html
{% if categories %}
<ul>
    {%  for cat in categories %}
    <li>
        <a href="{% url 'sharkommerce:item' cat.id %}">{{ cat }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
    <p>No items available.</p>
{% endif %}

sharkommerce/templates/sharkommerce/item.html
{% extends 'sharkommerce/base.html' %}
{% load static %}
{% load filters %}
{% block content %}

    {# card prodotto #}
    <div class="card mx-auto" style=" width: 25rem; margin-top: 50px; margin-bottom: 50px">
        <h3 style="text-align: center" class="card-title">{{ item.name }}</h3>
        <img class="card-img-top mx-auto" src="{{ item.image.url }}" alt="Card image cap" style="max-width: 200px; max-height: 300px; object-fit: scale-down">
        <div class="card-body">
            <div class="row">
                <p>{{ item.description }}</p>
            </div>
            <div class="row">
                Prezzo cad: {{ item.price }} €
            </div>
            <div class="row">
                Media recensioni prodotto: {{ avg_rate }}
                {% comment %}{% if avg_rate == 0%}
                    Ancora nessuna recensione
                {% else %}
                    {{ avg_rate }}
                {% endif %}{% endcomment %}
            </div>
        <div class="row">
            <p>Venditore: <a href="{% url 'sharkommerce:profile' item.seller.user.id %}">{{ item.seller }}</a> - Media
                recensioni: {{ item.seller.calculateAverageRate }}</p> {# bisogna calcolare la media delle recensioni già nel model. #}
        </div>
        <form id="item-form" class="form" method="post">
            {% csrf_token %}
            <div class="row">
                <div style="white-space:nowrap">
                    {% if not item.is_available %}
                        <p style="color:darkred">Momentaneamente non disponibile</p>
                    {% else %}
                        <label>{{ item_form.qty.label }}</label>
                        {{item_form.qty}}
                    {% endif %}
                </div>
            </div>
            <div class="row justify-content-center" style="margin-top: 20px">
            {# controlla che non venga rimesso attivo anche dalla view #}
                <input type="submit" class="btn btn-primary" value="Aggiungi al carrello" {% if item.qty == 0 %} disabled {% endif %}></input>
            </div>
        </form>
        </div>
    </div>
    <hr>

    {# carousel per le review del prodotto #}
    <h3 style="text-align: center">Cosa dicono del prodotto</h3>
    <div class="container" style="margin-bottom: 50px">
        {# carousel con le recensioni #}
        <div class="row mx-auto my-auto">
            <div id="prodReviewsCarousel" class="carousel slide w-100" data-ride="carousel">
            {% if reviews|length == 0 %}
        <p style="text-align: center">Ancora nessuna recensione per il prodotto</p>
    {% else %}
                <div class="carousel-inner w-100" role="listbox">
                    {% for rev in reviews %}
                        <div class="carousel-item {% if forloop.counter0 == 0 %}active{% endif %}">
                            <div class="col-md-4">
                                <blockquote class="blockquote text-center">
                                    {% if not is_logged %}
                                        <i style="color:darkblue">Accedi per leggere la recensione</i>
                                    {% else %}
                                        <h5>{{ rev.title }}</h5>
                                        <p class="mb-0">{{ rev.description }}</p>
                                    {% endif %}
                                    <p>Voto: {{ rev.vote }}</p>
                                    <footer class="blockquote-footer"><a
                                            href="{% url 'sharkommerce:profile' rev.purchase.buyer.user.id %}">{{ rev.purchase.buyer.user.username }}</a><cite
                                            title="Source Title">
                                        {{ rev.date|date:"d M Y" }}</cite></footer>
                                </blockquote>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev w-auto" href="#prodReviewsCarousel" role="button"
                   data-slide="prev">
                                        <span class="carousel-control-prev-icon bg-dark border border-dark rounded-circle"
                                              aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next w-auto" href="#prodReviewsCarousel" role="button"
                   data-slide="next">
                                        <span class="carousel-control-next-icon bg-dark border border-dark rounded-circle"
                                              aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    {% endif %}
    </div>

    {# prodotti consigliati #}
    <h3> Consigliati con questo prodotto</h3>
    <div class="row" style="margin-bottom: 50px">
        {% for elem in recommended_items %}
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'sharkommerce:item' elem.id %}">{{ elem.name }}</a></h5>
                        <img class="card-img-top rounded-circle border border-primary" src="{{ elem.image.url }}"
                             alt="Card image cap" style="max-width: 160px; max-height: 160px; object-fit: scale-down">
                        <p class="card-text">Prezzo: {{ elem.price }} € </p>
                        <p class="card-text">Venditore: <a
                                href="{% url 'sharkommerce:profile' elem.seller.user.id %}">{{ elem.seller }}</a></p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


    <script src="/static/sharkommerce/carousel_sold_prods.js"></script>

{% endblock %}